In [1]:
import pandas as pd
import numpy as np

In [2]:
a = pd.read_json('follow_id.json')

스크래피 멈춘곳 확인용
index 600000번부터 시작했는데.. 멈춘곳은 3286번째 인덱스
확인 필요

In [5]:
a

           insta_id
0       39306761196
1        3680315716
10      21951718049
100     11854821995
1000        7791277
...             ...
999995    602243194
999996   1706109079
999997   1670420896
999998   1377531449
999999    234948271

[1346600 rows x 1 columns]

In [6]:
a.index[a['insta_id'] == 1577496884].tolist()

[3286]

In [9]:
a.loc[3286]

insta_id    1577496884
Name: 3286, dtype: int64

In [35]:
###################################################################################

아이디별 라벨 확인용

In [3]:
id_label = pd.read_json('insta_id.json')

In [4]:
id_label

          insta_id target
0       4922234371    스포츠
1       5830178580    스포츠
2       8557008788    스포츠
3       1313265393    스포츠
4      16274303996    스포츠
...            ...    ...
15995    642527941  미디어감상
15996   4089277037  미디어감상
15997  26970769219  미디어감상
15998   6770029614  미디어감상
15999  33259336237  미디어감상

[16000 rows x 2 columns]

In [5]:
id_label= id_label.rename({'insta_id':'user_id_ls'}, axis = 'columns')

In [6]:
id_label

        user_id_ls target
0       4922234371    스포츠
1       5830178580    스포츠
2       8557008788    스포츠
3       1313265393    스포츠
4      16274303996    스포츠
...            ...    ...
15995    642527941  미디어감상
15996   4089277037  미디어감상
15997  26970769219  미디어감상
15998   6770029614  미디어감상
15999  33259336237  미디어감상

[16000 rows x 2 columns]

In [7]:
post = pd.read_json('sample.json')

In [8]:
post

,user_id_ls,post_date_ls,contents_ls,img_url_ls,url_ls
0,1319299351,2020-08-23 22:05:07,"[남자, 샤워실, 인줄]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEO5wk1n5Rr
1,1319299351,2020-08-23 19:34:31,"[해도, 해도, 안질리는, 물놀이, 휴가, 태닝, 계곡, 라면, 개먹은, 건, 안비밀]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEOohfxHpYl
2,1319299351,2020-08-21 21:01:51,"[럽스타, 그, 자체, 럽스타그램, 운동하는, 커플, 태닝]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEJo7Ytnz4x
3,1319299351,2020-08-21 13:38:56,"[이제, 야, 태는, 못하지만, 기태가, 남았다, 운동은, 멋짐, 휘트니스, 연산점...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEI2PaNnzQI
4,1319299351,2020-08-20 19:39:01,"[섹시한, 여자, 한컷, 럽스타그램, 태닝, 운동하는, 커플]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEG6p2OHCS5
...,...,...,...,...,...
712012,3592468483,2019-03-15 20:39:55,"[도봉산, 블랙, 야크, 대명산, 새해등산, 등산, 스타그램, 운동중독, 다이어터,...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/BvBxFXWhUjg
712013,3592468483,2019-03-13 23:11:07,"[겨울, 삼유캠, 예수를, 깊이, 생각하라, 캐캐캐캐캐, 콘콘콘콘콘, 캐콘, 지져스...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu84zJCBF_3
712014,3592468483,2019-03-13 09:54:37,"[새해, 첫날, 등산, 헬린이, 광교산, 등산]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu7dpTuBz76
712015,3592468483,2019-03-12 23:53:00,"[아듀, 아, 듀체지방]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu6YzARhKj7
712016,3592468483,2019-03-11 07:09:16,"[북한산, 백운대, 산장의, 마지막, 명산, 북한산, 백운대, 북한산, 백운대, 백...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu2BIg7hSay

In [9]:
post_label = pd.merge(id_label, post)

In [10]:
post_label

,user_id_ls,target,post_date_ls,contents_ls,img_url_ls,url_ls
0,5830178580,스포츠,2020-08-25 13:39:24,"[좋아요, 좋반, 여행, 바다, 출근전, 타임, 비드]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CETJeXtnbwo
1,5830178580,스포츠,2020-08-25 11:29:07,"[투피스, 입고, 다소곳, 모드]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CES6kDgnLvQ
2,5830178580,스포츠,2020-08-24 18:28:57,"[오늘도, 촬영할, 옷이, 산더미, 수요팅, 펀칭레이스, 절개트임, 블라우스, 부츠...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CERF0IcnL9O
3,5830178580,스포츠,2020-08-24 12:29:43,"[긴팔만, 입는나, 이쁜, 린넨, 야상발굔]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEQctCKHYZg
4,5830178580,스포츠,2020-08-23 17:27:11,"[데이트, 룩, 스토어, 팜]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEOZ879HUOJ
...,...,...,...,...,...,...
146637,39556686955,스포츠,2020-08-14 09:18:26,"[강산, 농원, 귀리오너라, 오리지널, 볶은, 귀리분말, 함유, 한포로, 포만감, ...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CD2W3XKJzQ3
146638,39556686955,스포츠,2020-08-11 17:23:38,"[더운, 날씨, 건강, 챙기세요, 배부른, 도라지, 수분, 보충필수, 구매, 좌표,...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CDvgAZ1JRl4
146639,3637588319,스포츠,2020-08-21 13:49:47,"[인생은, 축복이니, 낭비하면, 안됩니다, 미래는, 아무도, 모르는, 법이니까요, ...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEI3e6lnm9Q
146640,3637588319,스포츠,2020-08-13 00:34:57,"[여행이, 그러하듯이, 인생도, 빈틈에서, 얻을, 있는, 많다, 모두가, 완벽한, ...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CDy2KYEnn8P
146641,3637588319,스포츠,2020-08-13 00:33:11,"[숨을, 천천히, 내, 쉬며, 없이, 펼쳐진, 광활했던, 곳에, 집중했다, 해발, ...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CDy19ZBnF9k

In [11]:
post_label['target'].unique()

array(['스포츠'], dtype=object)

In [12]:
id_label.index[id_label['user_id_ls'] == 3637588319].tolist()

[1998]

In [13]:
insta_id_label = pd.read_json('insta_id_label.json')

In [15]:
insta_users = pd.read_json('insta_users.json')

In [16]:
insta_users

       hashtag            post_date       crawling_time     insta_id
0           운동  2020-08-21 13:38:56 2020-08-21 13:37:22   1319299351
1           운동  2020-08-21 13:38:36 2020-08-21 13:37:22   1458703146
2           운동  2020-08-21 13:38:35 2020-08-21 13:37:22  36593513387
3           운동  2020-08-21 13:38:30 2020-08-21 13:37:22   2353695326
4           운동  2020-08-21 13:38:12 2020-08-21 13:37:22  10229940161
...        ...                  ...                 ...          ...
135574   movie  2020-08-21 19:00:09 2020-08-21 20:21:10   1690786950
135575   movie  2020-08-21 18:59:18 2020-08-21 20:21:10  38769614076
135576   movie  2020-08-21 18:54:08 2020-08-21 20:21:10   8011539079
135577   movie  2020-08-21 15:55:52 2020-08-21 20:21:10  39992191790
135578   movie  2020-08-21 14:07:01 2020-08-21 20:21:10   8419953219

[135579 rows x 4 columns]

In [17]:
insta_users= insta_users.rename({'insta_id':'user_id_ls'}, axis = 'columns')

In [18]:
insta_users=insta_users.drop(['post_date','crawling_time'], axis=1)

In [19]:
insta_users

       hashtag   user_id_ls
0           운동   1319299351
1           운동   1458703146
2           운동  36593513387
3           운동   2353695326
4           운동  10229940161
...        ...          ...
135574   movie   1690786950
135575   movie  38769614076
135576   movie   8011539079
135577   movie  39992191790
135578   movie   8419953219

[135579 rows x 2 columns]

In [20]:
post_label = pd.merge(insta_users, post)

In [21]:
post_label

,hashtag,user_id_ls,post_date_ls,contents_ls,img_url_ls,url_ls
0,운동,1319299351,2020-08-23 22:05:07,"[남자, 샤워실, 인줄]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEO5wk1n5Rr
1,운동,1319299351,2020-08-23 19:34:31,"[해도, 해도, 안질리는, 물놀이, 휴가, 태닝, 계곡, 라면, 개먹은, 건, 안비밀]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEOohfxHpYl
2,운동,1319299351,2020-08-21 21:01:51,"[럽스타, 그, 자체, 럽스타그램, 운동하는, 커플, 태닝]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEJo7Ytnz4x
3,운동,1319299351,2020-08-21 13:38:56,"[이제, 야, 태는, 못하지만, 기태가, 남았다, 운동은, 멋짐, 휘트니스, 연산점...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEI2PaNnzQI
4,운동,1319299351,2020-08-20 19:39:01,"[섹시한, 여자, 한컷, 럽스타그램, 태닝, 운동하는, 커플]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEG6p2OHCS5
...,...,...,...,...,...,...
2379810,등산,3592468483,2019-03-15 20:39:55,"[도봉산, 블랙, 야크, 대명산, 새해등산, 등산, 스타그램, 운동중독, 다이어터,...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/BvBxFXWhUjg
2379811,등산,3592468483,2019-03-13 23:11:07,"[겨울, 삼유캠, 예수를, 깊이, 생각하라, 캐캐캐캐캐, 콘콘콘콘콘, 캐콘, 지져스...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu84zJCBF_3
2379812,등산,3592468483,2019-03-13 09:54:37,"[새해, 첫날, 등산, 헬린이, 광교산, 등산]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu7dpTuBz76
2379813,등산,3592468483,2019-03-12 23:53:00,"[아듀, 아, 듀체지방]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu6YzARhKj7
2379814,등산,3592468483,2019-03-11 07:09:16,"[북한산, 백운대, 산장의, 마지막, 명산, 북한산, 백운대, 북한산, 백운대, 백...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu2BIg7hSay

In [22]:
post_label['target'] = ''

In [23]:
post_label

,hashtag,user_id_ls,post_date_ls,contents_ls,img_url_ls,url_ls,target
0,운동,1319299351,2020-08-23 22:05:07,"[남자, 샤워실, 인줄]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEO5wk1n5Rr,
1,운동,1319299351,2020-08-23 19:34:31,"[해도, 해도, 안질리는, 물놀이, 휴가, 태닝, 계곡, 라면, 개먹은, 건, 안비밀]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEOohfxHpYl,
2,운동,1319299351,2020-08-21 21:01:51,"[럽스타, 그, 자체, 럽스타그램, 운동하는, 커플, 태닝]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEJo7Ytnz4x,
3,운동,1319299351,2020-08-21 13:38:56,"[이제, 야, 태는, 못하지만, 기태가, 남았다, 운동은, 멋짐, 휘트니스, 연산점...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEI2PaNnzQI,
4,운동,1319299351,2020-08-20 19:39:01,"[섹시한, 여자, 한컷, 럽스타그램, 태닝, 운동하는, 커플]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/CEG6p2OHCS5,
...,...,...,...,...,...,...,...
2379810,등산,3592468483,2019-03-15 20:39:55,"[도봉산, 블랙, 야크, 대명산, 새해등산, 등산, 스타그램, 운동중독, 다이어터,...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/BvBxFXWhUjg,
2379811,등산,3592468483,2019-03-13 23:11:07,"[겨울, 삼유캠, 예수를, 깊이, 생각하라, 캐캐캐캐캐, 콘콘콘콘콘, 캐콘, 지져스...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu84zJCBF_3,
2379812,등산,3592468483,2019-03-13 09:54:37,"[새해, 첫날, 등산, 헬린이, 광교산, 등산]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu7dpTuBz76,
2379813,등산,3592468483,2019-03-12 23:53:00,"[아듀, 아, 듀체지방]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu6YzARhKj7,
2379814,등산,3592468483,2019-03-11 07:09:16,"[북한산, 백운대, 산장의, 마지막, 명산, 북한산, 백운대, 북한산, 백운대, 백...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu2BIg7hSay,

In [24]:
insta_users['hashtag'].unique()

array(['운동', '등산', '라이딩', '자전거', '축구', '야구', '서핑', '골프', '헬스', '낚시',
       '카페스타그램', '카페투어', '감성카페', '카페추천', '인생샷카페', '전원카페', '카페탐방', '커피맛집',
       '분위기좋은카페', '홈카페', '유럽여행', '동남아여행', '여행스타그램', '여행에미치다', '해외여행',
       '국내여행', '일본여행', '유디니', '여행사진', '여행다녀왔습니다', '오늘뭐입지', '오오티디',
       '오오티디룩', '패션스타그램', '남자코디', '여자코디', '스트릿패션', '데일리룩', '데일리코디',
       '옷스타그램', '맛스타그램', '맛있다', '먹방', '먹스타그램', '맛집그램', '먹방투어', '존맛탱',
       '냠냠', '맛집탐방', '푸드스타그램', '반려견', '반려묘', '강아지', '댕댕이', '고양이', '펫스타그램',
       '산책', '애옹이', '집사', '사지말고입양하세요', '리그오브레전드', 'lol', '롤', '메이플스토리',
       '모바일', '게임', '게임스타그램', '게임추천', '겜스타그램', '온라인게임', '모바일게임', '메스타그램',
       '메스타', '폰게임', '스팀', '배그', '유튜브', '유튜버', '구독', '넷플릭스', 'netflix',
       '미드', '넷플릭스추천', '영드', '영화', '영화추천', '영화스타그램', 'movie'],
      dtype=object)

In [25]:
ls = [['운동', '등산', '라이딩', '자전거', '축구', '야구', '서핑', '골프', '헬스', '낚시'],
     ['카페스타그램', '카페투어', '감성카페', '카페추천', '인생샷카페', '전원카페', '카페탐방', '커피맛집',
       '분위기좋은카페', '홈카페'],
     ['유럽여행', '동남아여행', '여행스타그램', '여행에미치다', '해외여행',
       '국내여행', '일본여행', '유디니', '여행사진', '여행다녀왔습니다'],
     ['오늘뭐입지', '오오티디',
       '오오티디룩', '패션스타그램', '남자코디', '여자코디', '스트릿패션', '데일리룩', '데일리코디',
       '옷스타그램'],
     ['맛스타그램', '맛있다', '먹방', '먹스타그램', '맛집그램', '먹방투어', '존맛탱',
       '냠냠', '맛집탐방', '푸드스타그램'],
     ['반려견', '반려묘', '강아지', '댕댕이', '고양이', '펫스타그램',
       '산책', '애옹이', '집사', '사지말고입양하세요'],
     ['리그오브레전드', 'lol', '롤', '메이플스토리',
       '모바일', '게임', '게임스타그램', '게임추천', '겜스타그램', '온라인게임', '모바일게임', '메스타그램',
       '메스타', '폰게임', '스팀', '배그'],
     ['유튜브', '유튜버', '구독', '넷플릭스', 'netflix',
       '미드', '넷플릭스추천', '영드', '영화', '영화추천', '영화스타그램', 'movie']]

In [26]:
len(ls)

8

In [27]:
target_ls = ['스포츠', '카페', '여행', '패션', '맛집', '반려동물','게임','미디어감상']

In [28]:
for idx, category in enumerate(ls) : 
    for hashtag in category :
        post_label['target'] = np.where(post_label['hashtag'] == '{}'.format(hashtag), '{}'.format(target_ls[idx]), post_label['target'])

In [29]:
post_label[1200000:]

,hashtag,user_id_ls,post_date_ls,contents_ls,img_url_ls,url_ls,target
1200000,여행사진,4475720967,2019-08-27 18:15:42,"[잘, 땐, 천사, 샤페이, 샤페, 이쵸, 코, 샤페이크림, 베어코트, 샤페이]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/B1qXvfODPfr,여행
1200001,여행사진,4475720967,2019-08-27 12:58:50,"[처음, 가본, 글램핑, 다음엔, 에어컨이랑, 선풍기를, 가져가야지, 더운, 빼고는...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/B1pzev9DkLW,여행
1200002,여행사진,4475720967,2019-08-26 10:49:30,"[주말, 글램핑, 사람보다, 신난, 쵸코와, 크림, 글램핑, 샤페이, 샤페, 이쵸,...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/B1m_4kpDSwH,여행
1200003,여행사진,4475720967,2019-08-26 01:51:13,"[에어컨이, 고장난, 더운, 차, 안, 더위를, 탈출하고, 싶어, 창문에, 매달려,...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/B1mCSDpD9Nl,여행
1200004,여행사진,4475720967,2019-08-25 21:35:47,"[쵸코, 자동차, 탔어요, 사진, 찍으려고, 기다려, 하니, 기다리긴, 하는데, 어...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/B1llDM4D9I_,여행
...,...,...,...,...,...,...,...
2379810,등산,3592468483,2019-03-15 20:39:55,"[도봉산, 블랙, 야크, 대명산, 새해등산, 등산, 스타그램, 운동중독, 다이어터,...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/BvBxFXWhUjg,스포츠
2379811,등산,3592468483,2019-03-13 23:11:07,"[겨울, 삼유캠, 예수를, 깊이, 생각하라, 캐캐캐캐캐, 콘콘콘콘콘, 캐콘, 지져스...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu84zJCBF_3,스포츠
2379812,등산,3592468483,2019-03-13 09:54:37,"[새해, 첫날, 등산, 헬린이, 광교산, 등산]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu7dpTuBz76,스포츠
2379813,등산,3592468483,2019-03-12 23:53:00,"[아듀, 아, 듀체지방]",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu6YzARhKj7,스포츠
2379814,등산,3592468483,2019-03-11 07:09:16,"[북한산, 백운대, 산장의, 마지막, 명산, 북한산, 백운대, 북한산, 백운대, 백...",https://scontent-ssn1-1.cdninstagram.com/v/t51...,https://www.instagram.com/p/Bu2BIg7hSay,스포츠

In [30]:
post_label['hashtag'][1]

'운동'

In [31]:
import json

file_path = "./sample_plus_target.json"

json_data = []

for idx in range(len(post_label)) :
    json_data.append({
        "user_id_ls": post_label['user_id_ls'][idx],
        "post_date_ls": post_label['post_date_ls'][idx],
        "contents_ls": post_label['contents_ls'][idx],
        "img_url_ls": post_label['img_url_ls'][idx],
        "url_ls" : post_label['url_ls'][idx],
        "hashtag" : post_label['hashtag'][idx],
        "target" : post_label['target'][idx]
    })

with open(file_path, 'w') as outfile:
    json.dump(json_data, outfile)

TypeError: Object of type int64 is not JSON serializable

In [33]:
len(json_data)

2379815

In [38]:
type(json_data[0]['user_id_ls'])

numpy.int64

In [46]:
for data in json_data :
    data['user_id_ls'] = int(data['user_id_ls'])

In [50]:
with open(file_path, 'w') as outfile:
    json.dump(json_data, outfile)

In [ ]:
sample_plus_target = pd.read_json('sample_plus_target.json')

In [ ]:
sample_plus_target